[build]
  command = "echo 'No build command needed'"
  publish = "."

[env]
  API_KEY = "${API_KEY}"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  API_KEY = "${API_KEY}"
